apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prefectservers.prefect.io
spec:
  group: prefect.io
  scope: Namespaced
  names:
    plural: prefectservers
    singular: prefectserver
    kind: PrefectServer
  versions:
    - name: v3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sqlite:
                  type: object
                  properties:
                    storageClassName:
                      type: string
                    size:
                      type: string
                  required:
                    - storageClassName
                    - size
                postgres:
                  type: object
                  properties:
                    host:
                      type: string
                    port:
                      type: number
                    user:
                      type: string
                    passwordSecretKeyRef:
                      type: object
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                    database:
                      type: string
                settings:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
          required:
            - spec
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prefectworkpools.prefect.io
spec:
  group: prefect.io
  scope: Namespaced
  names:
    plural: prefectworkpools
    singular: prefectworkpool
    kind: PrefectWorkPool
  versions:
    - name: v3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                server:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                  required:
                    - name
                workers:
                  type: number
          required:
            - spec
